name: women_safety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_login: ^5.1.0
  flutter_phone_direct_caller: ^2.2.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
